In [ ]:
import torch

# checking for GPU connectivity
print(torch.cuda.is_available())

import pandas as pd

df = pd.read_parquet('eval_retrieval_pairs.parquet')
df.head()

False

,id,domain,stratum,year,title,abstract,social_post,model
0,W3128646645,biomedical_health,high_cited_recent,2021,Global Cancer Statistics 2020: GLOBOCAN Estima...,This article provides an update on the global ...,Just saw that 2020 had ~19.3M new cancer cases...,gpt-oss-120b
1,W3118615836,biomedical_health,high_cited_recent,2021,The PRISMA 2020 statement: an updated guidelin...,The Preferred Reporting Items for Systematic r...,Just learned the PRISMA guidelines got a big o...,gpt-oss-120b
2,W2889646458,biomedical_health,high_cited_recent,2018,Global cancer statistics 2018: GLOBOCAN estima...,This article provides a status report on the g...,Did you know 2018 saw ~18 million new cancer c...,gpt-oss-120b
3,W2891378911,biomedical_health,high_cited_recent,2018,PRISMA Extension for Scoping Reviews (PRISMA-S...,"Scoping reviews, a type of knowledge synthesis...",Just found out the PRISMA-ScR guide for scopin...,gpt-oss-120b
4,W3008827533,biomedical_health,high_cited_recent,2020,Clinical Characteristics of Coronavirus Diseas...,"BACKGROUND: Since December 2019, when coronavi...","Turns out the average COVID patient was 47 yo,...",gpt-oss-120b

In [ ]:

# loading dataframe

import pandas as pd

df = pd.read_csv('cleaned_metadata.csv')

# dropping unnamed columns (indexes and stuff created on downloads)
df = df.loc[:, ~df.columns.str.contains('^Unnamed:')]

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20500 entries, 0 to 20499
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 20500 non-null  object
 1   title              20500 non-null  object
 2   authors            20500 non-null  object
 3   abstract           20500 non-null  object
 4   date               20500 non-null  object
 5   year               20500 non-null  int64
 6   doi                20499 non-null  object
 7   url                20500 non-null  object
 8   venue              20334 non-null  object
 9   cited_by           20500 non-null  int64
 10  concepts           20500 non-null  object
 11  domain             20500 non-null  object
 12  stratum            20500 non-null  object
 13  embedding_string   20500 non-null  object
 14  bm25_index_string  20500 non-null  object
dtypes: int64(2), object(13)
memory usage: 2.3+ MB

In [ ]:
# generating a balanced domain dataframe to produce a balanced evaluation set
from math import inf


domain_list = df['domain'].unique()
min_len = inf

for domain in domain_list:
  seg_length = len(df[df['domain'] == domain])
  print(domain,' : ',seg_length)
  min_len = min(min_len,seg_length)

balanced_df = pd.DataFrame()

for domain in domain_list:
  balanced_df = pd.concat([balanced_df,df[df['domain'] == domain][:min_len - 450]])

balanced_df = balanced_df[:1800]
balanced_df.shape

biomedical_health  :  9000
nutrition_food_science  :  6000
neuroscience_psychology  :  3000
biology_genetics  :  1500
chemistry_toxicology  :  1000

(1800, 15)

In [ ]:
# =========================
# INSTALLS
# =========================
!pip install cerebras-cloud-sdk -q

import os
import re
import time
import pandas as pd
from cerebras.cloud.sdk import Cerebras

# ── CONFIG ────────────────────────────────────────────────────────────────────
CEREBRAS_API_KEY = "csk-j5m42fhnenkhcjd63cwmd3peeytw694nxjmnvdjd9rm8twkn"
MODEL            = "gpt-oss-120b"
REQUESTS_PER_MIN = 28
OUTPUT_PATH      = "eval_retrieval_pairs.parquet"
# ─────────────────────────────────────────────────────────────────────────────

client   = Cerebras(api_key=CEREBRAS_API_KEY)
interval = 60.0 / REQUESTS_PER_MIN

SYSTEM_PROMPT = """You are a social media post writer. You output ONLY the final post — no thinking, no preamble, no "Let's craft", no "Here's a tweet", no explanation before or after. Just the raw post text.

RULES:
- Write like a real person on Twitter/X, Reddit, or Instagram — not a science journalist
- Translate jargon into plain everyday words (e.g. "myocardial infarction" → "heart attack", "machine learning model" → "AI", "statistically significant" → "actually proven", "randomized controlled trial" → "real study")
- The post must contain a concrete factual claim drawn from the paper
- Use casual language, abbreviations, maybe 1-2 relevant emojis, and 1-3 hashtags
- Keep it under 240 characters where possible, but don't sacrifice the claim
- Do NOT mention the paper, authors, journal, or say "new study" — write as if sharing something you just learned
- Output ONLY the post text. No explanation, no quotes around it, no preamble."""

USER_TEMPLATE = """Paper title: {title}

Abstract: {abstract}

Write the social media post:"""


def parse_retry_after(error_message: str) -> float:
    match = re.search(r'(?:(\d+)m)?(\d+(?:\.\d+)?)s', str(error_message))
    if match:
        return float(match.group(1) or 0) * 60 + float(match.group(2)) + 2
    return 30.0


def generate_post(title: str, abstract: str, retries: int = 4) -> str | None:
    for attempt in range(retries):
        try:
            response = client.chat.completions.create(
                model=MODEL,
                messages=[
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user",   "content": USER_TEMPLATE.format(
                        title=title,
                        abstract=abstract[:1200]
                    )}
                ],
                temperature=0.85,
                max_tokens=1024,
                top_p=0.95,
            )
            content = response.choices[0].message.content
            if not content:
                content = response.choices[0].message.reasoning
            if not content:
                raise ValueError("Both content and reasoning are empty")

            # extract last non-empty line — reasoning models write the post last
            lines = [l.strip() for l in content.strip().splitlines() if l.strip()]
            post  = next(
                (l for l in reversed(lines)
                 if not l.lower().startswith(("let", "here", "we need", "craft", "sure", "okay", "alright"))),
                lines[-1]
            )

            # strip surrounding quotes if model wrapped the post in them
            post = post.strip('"').strip("'").strip()
            return post

        except Exception as e:
            err_str = str(e)
            if "429" in err_str or "rate" in err_str.lower():
                wait = parse_retry_after(err_str)
                print(f"  [Rate limit] Sleeping {wait:.0f}s...")
                time.sleep(wait)
            else:
                wait = 2 ** attempt
                print(f"  [attempt {attempt+1}] Error: {e} — retrying in {wait}s")
                time.sleep(wait)
    return None


# ── PREVIEW: test on 5 rows before full run ───────────────────────────────────
print("=" * 60)
print("PREVIEW — first 5 posts. Interrupt if quality is bad.")
print("=" * 60)
for _, row in balanced_df.head(5).iterrows():
    post = generate_post(row["title"], row["abstract"])
    print(f"\nTitle:  {row['title'][:80]}...")
    print(f"Domain: {row['domain']}")
    print(f"Post:   {post}")
    print("-" * 60)
    time.sleep(interval)

print("\nIf posts look good, run the next cell to process all rows.")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.8/97.8 kB 2.8 MB/s eta 0:00:00
============================================================
PREVIEW — first 5 posts. Interrupt if quality is bad.
============================================================

Title:  Global Cancer Statistics 2020: GLOBOCAN Estimates of Incidence and Mortality Wor...
Domain: biomedical_health
Post:   Did you know breast cancer just overtook lung cancer as the most common diagnosis? 2.3 M new cases in 2020 vs 2.2 M lung. Still, lung kills the most—1.8 M deaths. 😮 #cancerstats #health
------------------------------------------------------------

Title:  The PRISMA 2020 statement: an updated guideline for reporting systematic reviews...
Domain: biomedical_health
Post:   Just learned PRISMA got a 2020 makeover – 27 checklist items, fresh flow diagrams & an abstract guide to make systematic reviews way clearer. 🙌 #research #OpenScience
------------------------------------------------------------

Title:  Global cancer statistics 2018: GLOBOCAN estimates of incidence and mortality wor...
Domain: biomedical_health
Post:   Wow, 2018 had ~18 M new cancer cases and 9.6 M deaths worldwide. Lung cancer tops the list – it’s the #1 diagnosed and the #1 cause of death, making up ~12% of cases and 18% of deaths. 😱 #CancerStats #Health
------------------------------------------------------------

Title:  PRISMA Extension for Scoping Reviews (PRISMA-ScR): Checklist and Explanation...
Domain: biomedical_health
Post:   Turns out the PRISMA-ScR guide for scoping reviews has 20 must‑have items + 2 optional ones, built by a 24‑expert panel. Helps make those reviews way clearer. 📚✨ #Research #OpenScience
------------------------------------------------------------

Title:  Clinical Characteristics of Coronavirus Disease 2019 in China...
Domain: biomedical_health
Post:   Turns out the average COVID‑19 patient in China was 47, about half were women, and only ~6% hit ICU, needed a ventilator, or died. Fever shows up in ~90% of cases, cough in 68%, diarrhea is rare 🤒📊 #COVID19 #HealthFacts
------------------------------------------------------------

If posts look good, run the next cell to process all rows.

In [ ]:
from google.colab import files

# ── MAIN LOOP — run this cell only if preview looks good ─────────────────────
if os.path.exists(OUTPUT_PATH):
    existing = pd.read_parquet(OUTPUT_PATH)
    done_ids = set(existing["id"].tolist())
    print(f"Resuming — {len(done_ids)} rows already done.")
else:
    existing = pd.DataFrame()
    done_ids = set()

todo = balanced_df[~balanced_df["id"].isin(done_ids)].copy()
print(f"Rows to process: {len(todo)} | Model: {MODEL} | {REQUESTS_PER_MIN} RPM")
print(f"Estimated time: ~{len(todo) / REQUESTS_PER_MIN:.0f} minutes")

results = []

for i, (_, row) in enumerate(todo.iterrows()):
    post = generate_post(row["title"], row["abstract"])

    # print every post so you can monitor quality live
    if (i + 1) % 10 == 0:
      print(f"[{i+1}/{len(todo)}] {post}")

    results.append({
        "id":          row["id"],
        "domain":      row["domain"],
        "stratum":     row["stratum"],
        "year":        row["year"],
        "title":       row["title"],
        "abstract":    row["abstract"],
        "social_post": post,
        "model":       MODEL,
    })

    if (i + 1) % 200 == 0:
        chunk      = pd.DataFrame(results)
        combined   = pd.concat([existing, chunk], ignore_index=True)
        combined.to_parquet(OUTPUT_PATH, index=False)
        existing   = combined
        results    = []
        null_count = chunk["social_post"].isna().sum()
        print(f"\n  ✓ Checkpoint {i+1} — {len(existing)} saved | nulls: {null_count}\n")
        files.download('eval_retrieval_pairs.parquet')

    time.sleep(interval)

# ── FINAL SAVE ────────────────────────────────────────────────────────────────
if results:
    chunk    = pd.DataFrame(results)
    combined = pd.concat([existing, chunk], ignore_index=True)
    combined.to_parquet(OUTPUT_PATH, index=False)

print(f"\nDone. {len(combined)} pairs saved to {OUTPUT_PATH}")
null_total = combined["social_post"].isna().sum()
print(f"Null posts: {null_total} ({null_total/len(combined)*100:.1f}%)")
combined[["domain", "social_post"]].sample(5)

Resuming — 800 rows already done.
Rows to process: 1000 | Model: gpt-oss-120b | 28 RPM
Estimated time: ~36 minutes
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[10/1000] Turns out P. aeruginosa builds slimey biofilm forts that make it ~10× more resistant to antibiotics 😷. Even crazier, when it teams up with Streptococcus in a mixed biofilm, its nasty factor drops. #microbiology #antibioticresistance 🚀
[20/1000] Just learned that COVID patients have far fewer gut bacteria types and a spike in opportunistic bugs like Streptococcus and Veillonella, unlike flu patients who have a different gut mix. 🤒🦠 #GutHealth #COVID19
[30/1000] New text: "Got word that about 78% of adult ALL patients cleared all detectable disease after just one cycle of blinatum
[40/1000] Did you know >60% of the bugs that make us sick come from animals? Even COVID‑19 probably jumped from bats. Time to push One Health 🐾🌍 #Zoonoses #OneHealth
  [Rate limit] Sleeping 30s...
[50/1000] Did you know that as we get
[60/1000] Turns out tumors with more T‑cells respond better to checkpoint therapy. Boosting T‑cell infiltration (even with nanotech) can flip cold tumors hot 🔥💉 #cancer #immunotherapy
[70/1000] Did you know that beyond the classic PD‑1/CTLA‑4 blockers, researchers are now testing drugs that shut down LAG‑3, TIM‑3, TIGIT, VISTA and B7/H3 to boost anti‑cancer immunity? 🤯 #CancerResearch #Immunotherapy
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[80/1000] Turns out the blood pressure meds like ACE inhibitors and ARBs actually raise ACE2 – the same doorway COVID uses – but that also ramps up the protective Ang‑(1‑7) pathway. Might be why they help heart & lungs. 💊❤️ #COVID19 #HeartHealth
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[90/1000] Turns out we still diagnose COVID‑19 with a nasal swab RT‑PCR because a solid antibody test isn’t around yet 😷🧪 #COVID19 #Testing
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[100/1000] None
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[110/1000] African American women get lupus at roughly 3× the rate of white women 😮‍💨. The disease hits minorities harder, so we need more inclusive care 🙌 #LupusAwareness #HealthEquity
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[120/1000] Did you know ~3.8 billion people have HSV‑1, about 2/3 of folks under 50? And ~490 million have HSV‑2, ~13% of 15‑49 year olds, especially women in Africa 🌍 #HealthFacts #STD
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[130/1000] Turns out severe COVID makes your platelets go hyper‑active and stick to monocytes, causing those immune cells to crank up tissue factor – the clotting trigger. 😳🩸 #COVID19 #Clotting #Health
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[140/1000] None
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[150/1000] None
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[160/1000] None
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[170/1000] None
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[180/1000] Did you know you can get up to 60 markers on a single FFPE slide using just a regular fluorescence microscope? No fancy gear needed, and it even works with super‑resolution 🧪🔬 #Immunofluorescence #CancerResearch
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[190/1000] Turns out tiny air particles (PM2.5) make lungs with EGFR mutations more likely to turn cancerous – they draw in macrophages that spit out IL‑1β and push those cells into a tumor‑ready state 🌫️🫁 #AirPollution #LungCancer
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[200/1000] None

  ✓ Checkpoint 200 — 1000 saved | nulls: 46

  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[210/1000] None
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[220/1000] None
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[230/1000] Turns out severe COVID can mess with your heart – many patients show spikes in heart injury markers like troponin. 😬 #HeartHealth #COVID19
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[240/1000] Turns out the gut bugs in overweight folks are loaded with Firmicutes & Clostridia, letting LPS sneak through and spark inflammation → insulin resistance. 😳 #GutHealth #Obesity
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[250/1000] None
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[260/1000] Turns out after a heart attack your heart’s resident immune cells get mostly swapped out for blood‑borne monocytes that turn into new macrophages. 🚑🫀 #HeartHealth #Immunity
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[270/1000] Turns out vitamins A, C, D, E, B‑complex, iron, selenium & zinc are key for a strong immune system—being low on any of them can make you more prone to infections. Age‑specific supplements can help fix that 💪🦠 #Health #Immunity
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[280/1000] Turns out you can now label dozens of proteins on one tumor slice instead of one at a time—makes the readouts way more consistent and cheaper, which is huge for cancer immunotherapy 🚀 #cancerresearch #immunology
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[290/1000] None
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[300/1000] None
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[310/1000] Turns out only 146 of 2,656 AI‑in‑education papers from 2007‑18 made the final cut 🙈 Most of the work comes from CS/STEM and leans heavy on numbers‑heavy methods. #EdTech #AI 🚀
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[320/1000] #FutureOfWork"(13?) "#FutureOfWork" = 14? Count: #1F2u3t4u5r6e7O8f9W10o11r12k13 = 13 characters? Actually # counts as 1, then letters: F=2, u=3, t=4, u=5, r=6, e=7, O=8, f=9, W=10, o=11, r=12, k=13. So 13. So now 239+13 = 252 >240.
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[330/1000] Just saw that a Siamese‑RPN tracker can run at 160 FPS and still tops the VOT2015‑2017 real‑time benchmarks. That’s crazy fast and accurate! 🚀 #AI #ComputerVision #Tech
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[340/1000] Turns out swapping in a ResNet‑50 into a Siamese tracker and adding a spatial‑aware sampling trick makes it beat the leaderboard on OTB2015, VOT2018, UAV123 and LaSOT 🚀 #ComputerVision #AI
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[350/1000] They managed to get brain scans from over 10k 9‑year‑olds at 21 different sites and the images look consistent across locations 👀🧠 #BrainScience #KidsResearch
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[360/1000] Turns out, eco‑ads work best when they hit all 5 S’s: show friends doing it, make it a habit, tie it to who you are, spark feelings, and give something you can actually hold. 🌱💡 #Sustainability #Marketing #EcoHack
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[370/1000] Turns out if those early paranoid fears get too intense, your brain can’t push past the teen‑age fear stage and just falls back into paranoia, keeping the anxiety locked in. 😬 #MentalHealth #Anxiety #Psychology
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[380/1000] None
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[390/1000] None
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[400/1000] Fintech startups are slipping through loopholes and pumping up shadow‑bank lending – non‑bank credit grew about 30% since 2015 thanks to regulatory arbitrage 🚀 #FinTech #ShadowBanking #Finance

  ✓ Checkpoint 400 — 1200 saved | nulls: 87

  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[410/1000] Turns out reflexivity isn’t just a buzzword – it’s a nonstop, collaborative habit of constantly checking how your own biases, background, and context shape every step of a qualitative project. 🌱 #QualResearch #Reflexivity
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[420/1000] Just heard that AI in hospitals can actually copy the same biases we already see—like skewed diagnoses for minority patients—if we don’t guard the data. 😬 #AI #HealthTech #Ethics
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[430/1000] Turns out you can actually prove a *lack* of an effect by using the TOST method – it lets you reject any effect bigger than your smallest meaningful size. So you can say “no real impact” with confidence. 😎 #psychology #stats
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[440/1000] If you're dealing with depression and feel like you don’t have much support, you’re actually more likely to have worse symptoms, slower recovery, and struggle socially 😔. Feeling lonely makes depression outcomes even tougher. #MentalHealth #SupportMatters
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[450/1000] Students who used the new learning media scored about 15% higher on tests and were way more motivated 🙌 #EdTech #LearningBoost
[460/1000] Turns out a lot of students still don’t have the gadgets they need for online class, and shaky internet is a real pain 🤦‍♀️. #EdTech #RemoteLearning
[470/1000] Turns out Prolific & CloudResearch give you better data for less cash—about $2 per good response vs $4‑5 on MTurk and $8 on Qualtrics. They also ace attention checks. 🎯 #research #datascience
[480/1000] Turns out blended classes cut dropout for minority students compared to straight‑online or face‑to‑face courses. 📉 Students judge quality the same way no matter the format. #EdTech #HigherEd
[490/1000] Turns out qualitative research is basically an iterative process where you get closer to the thing you're studying and pull out new distinctions. Even numbers‑heavy studies have a qualitative side. #research #methodology 😊
[500/1000] Just saw that even a single glance at a fake headline makes it seem more true later—still true a week after, even if fact‑checkers flag it. 🤯 Social feeds are basically belief factories. #FakeNews #MediaLiteracy
[510/1000] Turns out most teacher‑training courses only teach us how to use a few classroom apps, but they don’t give us the full digital skill set we need for today’s tech‑heavy classrooms. 🖥️📚 #EdTech #TeacherLife
[520/1000] Turns out people vary way more than the group average suggests – the spread inside each person is 2‑4× bigger than the spread across the whole group. So our big‑picture stats might be way too optimistic. 🤯 #psychology #stats
[530/1000] Turns out after you nail a motor sequence, the brain’s dorsolateral striatum, prefrontal & secondary motor cortex fire stronger for that routine, while the hippocampus and dorsomedial striatum chill out. 🧠💪 #Neuro #Learning
[540/1000] Crazy tech: a robot can jam 6 tiny electrode threads (192 contacts) into the brain every minute with micron‑precision, and they’re seeing about a 70% spike‑yield. 🤯🧠 #NeuroTech #BrainInterface
[550/1000] Turns out stress isn’t just “feeling stressed” – it breaks down into 4 types: acute spikes, big life events, daily hassles, and long‑term chronic load. Each hits your body differently, so we need to measure them all. 🌱 #Health #StressScience
[560/1000] Just heard that quantum computers can actually speed up machine‑learning tasks, cutting big‑data crunch time dramatically 🚀🤖 #QuantumAI #FutureTech
[570/1000] Turns out AI tricks like supervised learning and matrix completion actually beat classic econ methods when estimating causal effects or optimal policies 🚀 #DataScience #Econ #AI
[580/1000] Adults with 4+ nasty childhood events are about twice as likely to smoke and binge drink. 😳 #Health #ACE #Wellness
[590/1000] Turns out a simple spinal fluid test for Aβ42, total tau & phospho‑tau can spot Alzheimer’s even before symptoms show – and the new fully‑automated kits are super precise and consistent. 🧠✨ #Alzheimers #Biomarkers
[600/1000] Turns out when a brand is pushed by an Instagram star, people trust the source more, like the brand more, feel like the star is right there with them, and even get a bit jealous vs. a regular celeb 🙃 #marketing #socialmedia

  ✓ Checkpoint 600 — 1400 saved | nulls: 17

[610/1000] Turns out when nurses actually listen to patients' needs and talk in a patient‑centered way, recovery is better. But stuff like hospital policies, noisy rooms, and busy shifts can block that. #PatientCare #NurseLife 😊
[620/1000] Turns out hanging out in city parks isn’t just nice—it actually helps people feel more connected and get moving, which lifts mood and health 🌳💪 #UrbanGreen #MentalHealth #GetOutside
[630/1000] Turns out most sports supplements are hype. Only caffeine, creatine, some buffering stuff and nitrate actually have solid proof of boosting performance. 💪 #SportsScience #Supplements
[640/1000] Did you know a single big quake can trigger hundreds of landslides, some of which block rivers and form lakes that might burst decades or even centuries later, flooding valleys far downstream 🌊⛰️ #Earthquake #Landslides #Nature
[650/1000] Crazy how med school shifted online – now about 24% of us are putting in >15 hrs/week on e‑learning, up from just 7% before COVID. Flexibility is the big win, but home distractions are still a pain. 📚💻 #MedEd #OnlineLearning
[660/1000] Did you know a literature review can actually be its own study? 🚀 It has distinct types, methods & can contribute original insights, not just a summary. #ResearchTips #AcademicLife
[670/1000] Turns out a handful of self‑driving prototypes are already out on public roads 🚗💨, but they still can’t guarantee safe behavior in super‑busy, messy traffic. #autonomous #selfdriving #tech
[680/1000] Turns out online classes actually keep the learning going even when schools shut down because of COVID‑19. 📚 But it only works if families have the right gear and internet – gotta check local conditions. #EdTech #COVID19
[690/1000] Turns out 56 experts signed up to revamp the PROCESS surgery case series guidelines and 45 actually finished the survey—80% response, and they reached unanimous agreement in round one. Only 3 items got tossed. 🙌 #Surgery #Research
[700/1000] Turns out docs who drown in paperwork are way more likely to feel burned out 😩. Even a few mindfulness or group chats can slash that stress. #DocLife #Burnout #SelfCare
[710/1000] Just saw that GPT‑4 can actually read text in images and even help interpret medical scans. But its mistakes could seriously harm patients, so we really need some rules around using AI in healthcare. 🤖🩺 #AI #HealthTech #Regulation
[720/1000] Turns out nurses who didn't get COVID‑19 training are way more scared, and that fear drops their job happiness, spikes stress, and makes them think about quitting. 😟 #NurseLife #MentalHealth
[730/1000] Thus final answer
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[740/1000] Did you know kids with epilepsy are split into 3 groups? 4 self‑limited focal types, 3 generalized ones, and 5 developmental/encephalopathy syndromes. Knowing the exact syndrome helps guide treatment 🙌 #Epilepsy #KidsHealth
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[750/1000] Turns out folks with repeat depression have lower DMN connectivity – meds seem to drive it, and it's linked to worse symptoms. First‑time, drug‑naïve cases don’t show it. 🧠💊 #Depression #BrainHealth
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[760/1000] Turns"5+1
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[770/1000] Turns out teens who stress about COVID and scroll a lot on socials 📱 get lonelier and more down 😞 More virtual hangouts with friends actually link to higher depression. #mentalhealth #COVIDteens
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[780/1000] Turns out cuffing your blood flow while you lift light can actually boost muscle size and strength, and even stop muscle loss when you’re stuck on the couch. 💪🏽🩸 #BFR #fitness #muscle
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[790/1000] Turns out people who planned to self‑isolate were way more likely to stock up on weird stuff like extra toilet paper 🧻. Info overload online fuels that panic buying. #COVID #Behavior
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[800/1000] Did you know ~1.8 B people (23% of us) live in areas that could see a 100‑year flood? 🌊 Most are in low‑income nations – 1.2 B in South/East Asia, with China & India alone covering over a third. #ClimateRisk #Floods

  ✓ Checkpoint 800 — 1600 saved | nulls: 0

  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[810/1000] Turns out most college kids say mental‑health apps actually cut their anxiety and depression symptoms and are super easy to use 🙌 #StudentWellness #DigitalTherapy
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[820/1000] Turns out it's not just the weather—places with poor resource access, weak local governance, and limited cultural knowledge get hit hardest by floods and heatwaves 🌡️💔 #ClimateJustice #Vulnerability
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[830/1000] This new EEG Conformer model beats all previous methods on three public brainwave datasets, nailing motor imagery and emotion tasks 🤯 #AI #NeuroTech
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[840/1000] Did you know major depression costs the U.S. economy over $210 billion a year? 😱 And the number of adults dealing with it jumped about 12% from 2010 to 2018. #MentalHealth #Economics
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[850/1000] Turns out folks who find random nonsense sounding deep are way more likely to rate fake news as true and can’t tell real from fake as well. Over‑claiming your know‑how does the same, while big‑brain analytic thinking cuts the fake‑news belief. 🤯 #FakeNews #Psychology
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[860/1000] Just saw that AlphaFold 3 can predict protein‑ligand binding shapes way better than the best docking programs out there. 🎯💊 #AI #ProteinDesign
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[870/1000] Turns out cancer isn’t just about DNA swaps – tumors can literally reshape themselves, using epigenetic switches and even their microbiome to grab new powers. Even old senescent cells join the party. #cancer #biology 🧬🔬
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[880/1000] Turns out tinkering with a tiny RNA called U1 snRNP can make cancer cells zip around 5‑times faster. Low‑dose U1 blocking spikes migration/invasion up to 500%, while boosting U1 slows them down. 🚀🔬 #CancerResearch #CellMigration
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[890/1000] Just tried QIIME 2’s q2‑feature‑classifier and the naive‑Bayes, BLAST+ and VSEARCH options actually hit species‑level accuracy equal to or better than the classic RDP/BLAST pipelines 🚀 #microbiome #bioinfo
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[900/1000] Count quickly: "Tried"(5) space1=6 "ShinyGO"(7)=13 space=14 "–"(1)=15 space=16 "a"(1)=17 space=18 "web"(3)=21 space=22 "app"(3)=25 space=26 "that"(4)=30 space=31 "lets"(4)=35 space=36 "you"(3)=39 space=40 "explore"(7)=47 space=48 "gene"(4)=52 space=53 "sets"(4)=57 space=58 "with"(4)=62 space=63 "graphs"(6)=69 space=70 "and"(3)=73 space=74 "pulls"(5)=79 space=80 "pathway"(7)=87 space=88 "pics"(4)=92 space=93 "straight"(8)=101 space=102 "from"(4)=106 space=107 "KEGG"(4)=111
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[910/1000] DIAMOND’s latest upgrade can line up proteins across the whole tree of life in just a few hours, and it’s just as sensitive as BLASTP. 🚀 #Bioinformatics #Genomics
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[920/1000] Turns out cannabis has tons of gene copy number variation and SNPs, so CRISPR editing its THC/CBD pathways is way harder than we thought. 🤯 #cannabis #geneediting #biohack
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[930/1000] Just saw that the CUB-200-2011 bird dataset now has roughly double the images per species and comes with bounding boxes, part locations, and attribute tags. Perfect for training AI on birds 🐦📸 #AI #Birds #Dataset
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[940/1000] Just learned that scientists cataloged 49 single‑base, 11 doublet, 4 clustered and 17 indel mutational signatures from >84 M mutations across ~4.6k genomes and 19k exomes. 😲 #cancer #genomics
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[950/1000] Just found out miRDB can predict 3.5M miRNA targets across 5 species and even gives cell‑specific hits for 1k+ cell lines. Super handy for gene regulation work! 🚀 #Bioinformatics #Genomics
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[960/1000] Just learned we finally have a full human genome map – all chromosomes (except Y) are gap‑free, adding ~200 M extra bases and ~2 k new gene candidates, about 100 of which look like real proteins. 🚀🧬 #genomics #DNA
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[970/1000] Turns out you can grab 4‑km monthly climate data back to 1958, and it lines up with station temps and runoff way better than older grids. 🌍💧 #climate #data #science
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[980/1000] Turns out using long‑read tech can clean up old vertebrate genomes – we’ve added missing chunks and fixed tons of errors, even spotting false gene copies and weird bat chromosome breaks 🦇🔬 #genomics #DNA
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[990/1000] Did you know the Arctic is heating up about 4× faster than the rest of Earth since ’79? 🤯 That's way more than the 2‑3× we usually hear. #climatechange #Arctic
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
  [Rate limit] Sleeping 30s...
[1000/1000] Just saw that tweaking image augmentations can push ImageNet top‑1 to 83.5% – beating the old best by 0.4%. Same tricks drop CIFAR‑10 error to 1.5%, shaving off 0.6% 🔥📈 #AI #DeepLearning

  ✓ Checkpoint 1000 — 1800 saved | nulls: 0

Done. 1800 pairs saved to eval_retrieval_pairs.parquet
Null posts: 175 (9.7%)

,domain,social_post
1278,neuroscience_psychology,Turns out babies don’t just soak up everything...
1159,neuroscience_psychology,"Turns out, eco‑ads work best when they hit all..."
1192,neuroscience_psychology,"Turns out Sgr A*'s shadow is a bright, thick r..."
1265,neuroscience_psychology,Turns out firms that actually build AI capabil...
470,biomedical_health,Just saw that in a huge review of 4.5 M adults...

In [ ]:
models = client.models.list()
for m in models.data:
    print(m.id)

response = client.chat.completions.create(
    model="gpt-oss-120b",
    messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "Say the word hello."}
    ],
    max_tokens=20,
)
print(response)
print("---")
print(response.choices[0].message.content)
print("---")
print(response.choices[0].finish_reason)

gpt-oss-120b
zai-glm-4.7
ChatCompletionResponse(id='chatcmpl-8aa8e3f8-d279-4f4c-913d-fe7b9d86c111', choices=[ChatCompletionResponseChoice(finish_reason='stop', index=0, message=ChatCompletionResponseChoiceMessage(role='assistant', content='hello', reasoning='We just need to comply: "hello".', tool_calls=None), logprobs=None, reasoning_logprobs=None)], created=1779913392, model='gpt-oss-120b', object='chat.completion', system_fingerprint='fp_46358675aa6b1ba4d98d', time_info=ChatCompletionResponseTimeInfo(completion_time=0.012858176, prompt_time=0.002504162, queue_time=0.004005839, total_time=0.020956754684448242, created=1779913392.3242085), usage=ChatCompletionResponseUsage(completion_tokens=20, completion_tokens_details=ChatCompletionResponseUsageCompletionTokensDetails(accepted_prediction_tokens=0, rejected_prediction_tokens=0, reasoning_tokens=9), prompt_tokens=85, prompt_tokens_details=ChatCompletionResponseUsagePromptTokensDetails(cached_tokens=0), total_tokens=105), service_tier=None)
---
hello
---
stop

In [ ]:
import pandas as pd

df1 = pd.read_parquet('eval_retrieval_pairs_first_half.parquet')
df2 = pd.read_parquet('eval_retrieval_pairs_second_half.parquet')

df = pd.concat([df1,df2])
df.to_csv('post_paper_pairs.csv')